//
// Created by KAVOSH on 2/28/2024.
//
#ifndef MINMAXHEAP_CONFIGDIR_INL
#define MINMAXHEAP_CONFIGDIR_INL

#define TEST_IS_MIN_MAX_HEAP
#define REDUCE_MINMAX_HEAP_SIZE

#endif //MINMAXHEAP_CONFIGDIR_INL
